"""
> module lightmatrix
>> type __class__
>>> type __class__
>>> str __name__
>>> tuple __bases__
>>> dict __dict__
>> str __name__
>> str __file__
>> module hub
>>> type __class__
>>> str __name__
>>> str __version__
>>> int BACK
>>> int BOTTOM
>>> type BT_VCP
>>> int FRONT
>>> type Image
>>> int LEFT
>>> int RIGHT
>>> int TOP
>>> type USB_VCP
>>> Battery battery
>>> bluetooth bluetooth
>>> type button
>>> dict config
>>> Display display
>>> function file_transfer
>>> function info
>>> function led
>>> Motion motion
>>> type port
>>> function power_off
>>> function repl_restart
>>> function reset
>>> Sound sound
>>> function status
>>> supervision supervision
>>> function temperature
>> list ORIENTATIONS
>> list FACES
>> function rotate_orientation
>> function get_current_orientation
>> function set_current_orientation
>> type LightMatrix
>>> type __class__
>>> function __init__
>>> str __module__
>>> str __name__
>>> str __qualname__
>>> function write
>>> tuple __bases__
>>> dict __dict__
>>> function off
>>> function set_pixel
>>> function show
>>> list _ALLOWED_EFFECTS
>>> function show_image
>>> function play_animation
>>> function start_animation
>>> function _perform_animation
>>> function get_orientation
>>> function set_orientation
>>> function rotate
"""
