"""
> module motionsensor
>> type __class__
>>> type __class__
>>> str __name__
>>> tuple __bases__
>>> dict __dict__
>> str __name__
>> str __file__
>> module hub
>>> type __class__
>>> str __name__
>>> str __version__
>>> int BACK
>>> int BOTTOM
>>> type BT_VCP
>>> int FRONT
>>> type Image
>>> int LEFT
>>> int RIGHT
>>> int TOP
>>> type USB_VCP
>>> Battery battery
>>> bluetooth bluetooth
>>> type button
>>> dict config
>>> Display display
>>> function file_transfer
>>> function info
>>> function led
>>> Motion motion
>>> type port
>>> function power_off
>>> function repl_restart
>>> function reset
>>> Sound sound
>>> function status
>>> supervision supervision
>>> function temperature
>> function sleep_ms
>> type MotionSensor
>>> type __class__
>>> function __init__
>>> str __module__
>>> str __name__
>>> str __qualname__
>>> tuple __bases__
>>> dict __dict__
>>> str BACK
>>> str DOWN
>>> str FALLING
>>> str FRONT
>>> str TAPPED
>>> str UP
>>> function align_to_model
>>> function get_orientation
>>> function _orientation_from_string
>>> function get_pitch_angle
>>> function get_roll_angle
>>> function get_yaw_angle
>>> function reset_yaw_angle
>>> str LEFT_SIDE
>>> str RIGHT_SIDE
>>> function wait_for_new_orientation
>>> str SHAKEN
>>> str DOUBLE_TAPPED
>>> function get_gesture
>>> function was_gesture
>>> function wait_for_new_gesture
"""
