"""
> module statuslight
>> type __class__
>>> type __class__
>>> str __name__
>>> tuple __bases__
>>> dict __dict__
>> str __name__
>> str __file__
>> module hub
>>> type __class__
>>> str __name__
>>> str __version__
>>> int BACK
>>> int BOTTOM
>>> type BT_VCP
>>> int FRONT
>>> type Image
>>> int LEFT
>>> int RIGHT
>>> int TOP
>>> type USB_VCP
>>> Battery battery
>>> bluetooth bluetooth
>>> type button
>>> dict config
>>> Display display
>>> function file_transfer
>>> function info
>>> function led
>>> Motion motion
>>> type port
>>> function power_off
>>> function repl_restart
>>> function reset
>>> Sound sound
>>> function status
>>> supervision supervision
>>> function temperature
>> type StatusLight
>>> type __class__
>>> str __module__
>>> str __name__
>>> str __qualname__
>>> tuple __bases__
>>> dict __dict__
>>> function off
>>> function on
>> dict _COLORMAP
"""
